# Generated by Django 2.2 on 2020-10-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20201012_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='', max_length=125),
        ),
    ]
